[tool.poetry]
name = "pyre-test"
version = "0.1.0"
description = "test pyre behavior"
authors = ["Ohori, Ryuichi <ohori.ryuichi@fujitsu.com>"]

[tool.poetry.dependencies]
python = "^3.7.1,<3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
