on: [push]
jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install --no-interaction
      - name: install pyre
        run: poetry add -D pyre-check
      - name: pyre
        run: poetry run pyre --source-directory src check
